### ISSUE TITLE
detector = RetinaFace(backbone='RESNET50') not found

### ISSUE THREAD

**Issue by hyun105** [TanyaChutani/Face-Mask-Detection-Tf2.x#3]
Maybe the service on 'fdet' has been terminated.

urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by hyun105** [comment]
Fixed by modifying dropbox url inside retinaface.py

![스크린샷, 2021-05-12 11-18-46](https://user-images.githubusercontent.com/42713590/117908708-e0ab3800-b313-11eb-8c33-ea6136b36ce4.png)

https://github.com/acnazarejr/fdet/pull/13/commits/89f176634535b72fc1339f89833db76a3c80aa65

**Comment by TanyaChutani** [comment]
Cool, Thanks! I will also modify my notebook now.

**Comment by hyun105** [comment]
Tested and found that MOBILENET url is not valid

**Comment by TanyaChutani** [comment]
Ok, I have raised the issue on fdet repository. Let's wait or you can use any other face detector.
